### ISSUE TITLE
Sometimes eating has a too big delay

### ISSUE THREAD

**Issue by TheUser816** [Seveningful/BayMaxAC#11]
Sometimes, when eating something, there’s a bigger delay than in vanilla minecraft before you consumed the food.
Server-Version: 1.8
Plugin-Version: Alpha-04

**Comment by Seveningful** [comment]
It's normal. Since the client sends too many packets it's detected as "PacketSpamming". Baymax cancels every packet that's detected as PacketSpamming. 
That said i'll try to make it closer to vanilla :)

**Comment by Seveningful** [comment]
Fixed in the next version (Alpha-08)
