### ISSUE TITLE
Legit players getting flagged for Killaura / Aimbot

### ISSUE THREAD

**Issue by TheUser816** [Seveningful/BayMaxAC#12]
Legit players can get flagged for Killaura : Aimbot (about 85%, 99%) or Killaura (80%/100%) when fighting normal.
This is with learning 2 times (2x restarts).

**Comment by Seveningful** [comment]
Could you provide any videos ?
The version used ?

**Comment by TheUser816** [comment]
Server-Version: 1.8
Plugin-Version: Alpha-04

Can’t provide any videos for now, but the users are fighting normally.
I’ll try it later with Alpha-041 and then report back.

**Comment by Seveningful** [comment]
Ok :)

**Comment by Seveningful** [comment]
Should be fixed in Alpha-042 :) Tell if it's not the case
