### ISSUE TITLE
Feature | Training the machine

### ISSUE THREAD

**Issue by Games4k** [Seveningful/BayMaxAC#13]
The best thing that you can make is to make us able to train the plugin and make custom heuristics.
Something like this: https://www.spigotmc.org/threads/anti-cheat-machine-learning-anti-killaura.145835/

I'm sure you can do that, but it probably takes a lot of time :P

**Comment by Seveningful** [comment]
Will be implemented around the version 08 or 09 got some fixes to do before :)

**Comment by Games4k** [comment]
Ok! This would be really cool. When I finish lobby, I'll test new version. I'm corectly setting up my new server

**Comment by Seveningful** [comment]
Will be implemented in version 09

**Comment by Seveningful** [comment]
Done :)
