### ISSUE TITLE
High ping and low TPS server making player flagged for KillAura / Aimbot

### ISSUE THREAD

**Issue by TheFates123** [Seveningful/BayMaxAC#14]
12.5-15.5 TPS usually making player flagged for Criticals (70%) , KillAura/Aimbot (90%) and the high ping players (from 100-300 ping) always getting flagged for KillAura/Aimbot.

I restarted the server for 5x times and edited the kick percentage to 45 but it still getting false flag.

**Comment by Seveningful** [comment]
You should raise the kick percentage if you want less people to get kicked.
Lag and TPS conditions haven't been implemented yet
Also how can a 12.5 TPS server run ? 
Try the new version and tell me what happens (Alpha-05)

**Comment by Games4k** [comment]
> 12.5-15.5 TPS usually making player flagged for Criticals (70%) , KillAura/Aimbot (90%) and the high ping players (from 100-300 ping) always getting flagged for KillAura/Aimbot.
>
> I restarted the server for 5x times and edited the kick percentage to 45 but it still getting false flag.

U can fix it with this plugin https://www.spigotmc.org/resources/conditionalcommands.14295/

**Comment by Seveningful** [comment]
Baymax will have a TPS threshold (18.5) and will be automatically disabled when it's lower than that.
Lag detection is being slowly implemented.
Thanks :)
