### ISSUE TITLE
Killaura/Aimbot False Positive

### ISSUE THREAD

**Issue by Spazzinq** [Seveningful/BayMaxAC#17]
If you leave your mouse still and hit an entity, it detects you for aimbot/killaura.

[https://youtu.be/mt03kpvklss](https://youtu.be/mt03kpvklss)

[https://youtu.be/d3WtSsB-oFE](https://youtu.be/d3WtSsB-oFE)

(I had the LiquidBounce client on but did not use any of the cheats)

**Comment by Seveningful** [comment]
It's fixed in the dev version. It will be up tomorrow :)
