### ISSUE TITLE
Exceptions...

### ISSUE THREAD

**Issue by Personinblack** [Seveningful/BayMaxAC#23]
https://hastebin.com/ewigukayul.md
https://hastebin.com/zuwejuyiyu.bash

**Comment by Seveningful** [comment]
Provide me your plugin version. 
Obfuscation seed changes every build i can't decode that without knowing what version you're using

**Comment by Personinblack** [comment]
It's Alpha-07.

**Comment by Personinblack** [comment]
Here is another one with the latest version. (Alpha-0.72)
https://hastebin.com/adamevutoz.bash

**Comment by Seveningful** [comment]
Ok I'll fix everything i can for the next update and thanks :)

**Comment by Seveningful** [comment]
Fixed in the next version (Alpha-08) Thanks ;)
