### ISSUE TITLE
Detects as Vanilla Aim while cheating with KillAura

### ISSUE THREAD

**Issue by Personinblack** [Seveningful/BayMaxAC#24]
While I'm pvping with KillAura I get detected for Vanilla Aim too much. It eventually detect the KillAura but still it shouldn't inform while its not sure what I am doing. This confuse me alot.

![229](https://user-images.githubusercontent.com/24732321/28438911-75f4341c-6da8-11e7-9def-80fa2a8b9bf6.png)

**Comment by Seveningful** [comment]
Look at the config file please
