### ISSUE TITLE
NPE Spam

### ISSUE THREAD

**Issue by Spazzinq** [Seveningful/BayMaxAC#26]
[https://gist.github.com/Spazzinq/3f6e65c63fca22f7bd71181c7de24226](https://gist.github.com/Spazzinq/3f6e65c63fca22f7bd71181c7de24226)

**Comment by Seveningful** [comment]
Provide me your plugin version. 
Obfuscation seed changes every build i can't decode that without knowing what version you're using

**Comment by Spazzinq** [comment]
I always use the latest version, unless it is incompatible with 1.8 (Alpha-07)

**Comment by Spazzinq** [comment]
Fixed in latest update
