### ISSUE TITLE
Erreur quand je tape une entity

### ISSUE THREAD

**Issue by theocerdan** [Seveningful/BayMaxAC#27]
https://pastebin.com/C1Tgm7a9

**Comment by Seveningful** [comment]
Quelle est la version du plugin utilisée ?

**Comment by theocerdan** [comment]
http://i.imgur.com/TrclFnf.png
http://i.imgur.com/qgvZlhx.png
http://i.imgur.com/nVaWyO2.png

**Comment by Seveningful** [comment]
Fix dans la dernière version (Alpha-08)
