### ISSUE TITLE
Fly false positive

### ISSUE THREAD

**Issue by coookiemonsterm** [Seveningful/BayMaxAC#29]
http://i.imgur.com/0Ge8mTL.png When just double tapping space bar a lot it comes up as your flying and I also get kicked for multidirectional sprint which im just running around around aswell. Also it would be nice if you could add a feature where we can select what we want to have him testfor and what not to test for.

**Comment by coookiemonsterm** [comment]
Note pressing space then wasd while holding sprint can set off multidrectional sprint. I changed it to 1000% kick so I wouldn't be kicked while testing and I just got this
![image](https://user-images.githubusercontent.com/30368792/28491195-a32afd20-6ee4-11e7-83cf-63590a1a2a7d.png)

**Comment by Games4k** [comment]
Wow..

**Comment by coookiemonsterm** [comment]
I thought the same thing XD. That was just in vanilla mc just me juping around

**Comment by Seveningful** [comment]
Fixed in the next version, Thank you :)
