### ISSUE TITLE
Faux positif

### ISSUE THREAD

**Issue by hugo4715** [Seveningful/BayMaxAC#30]
Pas mal de faux positif sur le killaura :(
Je suis sans cheat, et le plugin m'a detecté deux fois de suite, la premiere a 99.7% et la deuxieme a 100%
Ca me detecte aussi pour un truc je sais meme pas ce que c'est "CraftPingflow: TOO_ABSOLUTLY_LONG"
Et la reach aussi de temps en temp elle trigger

Info: 

- serveur: play.gurudev.eu 
 -date: le 23/07/2017 vers 16h

**Comment by hugo4715** [comment]
En fait j'arrive a trigger la reach volontairement (faut just jitter et s'approcher jus'qu'a etre en limite de hitbox a chaque coup)

**Comment by Seveningful** [comment]
La version présente sur le serveur de test n'est absolument pas stable, c'est des versions compilées à la volée, donc c'est normal

**Comment by hugo4715** [comment]
Ok, ca serai possible de mettre une version stable dessus?
