### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by coookiemonsterm** [Seveningful/BayMaxAC#31]
Is there anyway I can have to it send to like discord if no staff members are online to tell me someone is hacking

**Comment by Seveningful** [comment]
Hum you mean a discord bot ?

**Comment by coookiemonsterm** [comment]
yea it would be cool to have

**Comment by coookiemonsterm** [comment]
I don't know how much work it would be so it doesn't have to be done but it's just a suggestion like if it's possible. I know that mineplex do it with Gwen to SLACK

**Comment by Seveningful** [comment]
@coookiemonsterm you mean something like this ? 

![image](https://image.prntscr.com/image/RqFQYWmHTo_y3yNT55p2bw.png)

**Comment by coookiemonsterm** [comment]
I love you!

**Comment by Seveningful** [comment]
Done. :)
