### ISSUE TITLE
Feature and FP

### ISSUE THREAD

**Issue by zikdriver** [Seveningful/BayMaxAC#32]
- My setback fp on slap (https://i.imgur.com/Jj5XSlo.png) was not really fixed.
- Than have PingSpoof a fp: https://i.imgur.com/AipRVVM.png The Server TPS has 20 and my Ping was 35ms
- Can you make everything adjustable?
- Can you add that you get for each setback a message? (Because: i can not say for what I am gesetbacked. And yes i have (/baymax verbose)

**Comment by Seveningful** [comment]
1. What the heck is "setback fp on slap"
2. Fixed in the last update
3. No, The values won't be configurable, at least not until the release
4 Once again what the heck is a "setback"

**Comment by Seveningful** [comment]
Try the last version, maybe what you mean is "rollback", I don't know. Should be fixed :)
