### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by Spazzinq** [Seveningful/BayMaxAC#34]
The version is in the error (Alpha-081) [https://gist.github.com/Spazzinq/f95d8411821debf0689d18599b35925c](https://gist.github.com/Spazzinq/f95d8411821debf0689d18599b35925c)

**Comment by Spazzinq** [comment]
https://gist.github.com/Spazzinq/59361e8964f8f946868405b3c400b501 (Alpha-09)

**Comment by Seveningful** [comment]
I didn't fix anything last version so it's normal
I'll fix that tomorrow

**Comment by Spazzinq** [comment]
I know, but just in case you wanted to know :)

**Comment by Spazzinq** [comment]
It was the ProtocolLib version, it is now fixed with the latest dev build
