### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by coookiemonsterm** [Seveningful/BayMaxAC#35]
The /train command doesn't work.
I get 25.07 09:03:41 [Server] INFO coookiemonsterm issued server command: /baymax:train 25.07 09:03:41 [Server] ERROR null 25.07 09:03:41 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing 'baymax:train' in eu.gurudev.baymax.d.b(train) 25.07 09:03:41 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:148) ~[spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650) ~[spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1353) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131] 25.07 09:03:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131] 25.07 09:03:41 [Server] INFO Caused by: java.lang.ArrayIndexOutOfBoundsException: 1 25.07 09:03:41 [Server] INFO at eu.gurudev.baymax.d.b.execute(b.java:23) ~[?:?] 25.07 09:03:41 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.11.2.jar:git-Spigot-b605b31-f4822eb] 25.07 09:03:41 [Server] INFO ... 14 more

I'm also being spammed with 
25.07 09:01:48 [Server] INFO [Baymax] [DEBUG] Time 1500987656710 -- 1500987708335 25.07 09:01:48 [Server] INFO [Baymax] [DEBUG] -1516.699999988079,111.99323530006211,688.6999999880791 25.07 09:01:48 [Server] INFO java.io.IOException: Cannot run program "traceroute": error=2, No such file or directory

**Comment by Seveningful** [comment]
Disable debug so you don't get spammed
The train command isn't documented yet and it does work you just don't know how to use it
What kind of server are you using that doesn't have traceroute lol

**Comment by coookiemonsterm** [comment]
Idk XD its from rabbitnode or something XD
