### ISSUE TITLE
1.12 support?

### ISSUE THREAD

**Issue by Games4k** [Seveningful/BayMaxAC#4]
It looks like a good anticheat, but it needs 1.12 support...
Are you planing to add it any time soon?

Also, why are u using mediafire? Use default spigot uploading tool.

**Comment by Games4k** [comment]
Author said that he will fix it in the next versions, so i'll close it for now :)

**Comment by Seveningful** [comment]
I was using mediafire because the fil was way too big :)
I splitted the libs and the actual plugin so it's easier to install and update
