### ISSUE TITLE
KillAura | Aimbot false positive

### ISSUE THREAD

**Issue by Flynrod** [Seveningful/BayMaxAC#5]
English:
Hi! I have a small problem with KillAura/Aimbot detection. I'm not using a cheat and I'm flagged for cheat.

Français:
Salut! J'ai un petit problème avec la détection du KillAura/Aimbot. Je n'utilise pas de cheat et je suis détecté pour cheat.

Video: https://www.youtube.com/watch?v=GgzZxnF5yco

**Comment by Seveningful** [comment]
Ca n'arrive que si l'autre joueur ne bouge pas càd qu'il n'envoie pas d'activité au serveur ce qui rend les données faussées. Je corrige ça pour la prochaine version :) 
Merci !

**Comment by Flynrod** [comment]
Pas de problème ! :)

**Comment by Seveningful** [comment]
Voilà c'est corrigé dans la version Alpha-03 :)
